### ISSUE TITLE
Updating the psk password

### ISSUE THREAD

**Issue by saket424** [tmunzer/api-test-tool#2]
@tmunzer ,
I managed to successfully use the API to change the wifi password using
PUT https://cloud-va2.aerohive.com/xapi/beta/configuration/ssids/{ssid-id}/psk?ownerId={ownerid}
{"psk":{"encryptionMethod":"CCMP","keyType":"ASCII","keyValue":"foobar!!"}}

It however did not push the new delta to the device and made the change only in the HiveManager NG

Is there an API to force the delta to the device(s) instead of having to do it manually ?

**Comment by tmunzer** [comment]
Hi Saket424,

There is currently no way to deploy the changes for now. This is something planed for a future release. 
Please use the developer alias Developer.Portal@aerohive.com for your question regarding the APIs, more people will be able to answer to your questions.

Thanks
